# Generated by Django 4.0.3 on 2025-03-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiabitesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('glycemic_index', models.IntegerField()),
                ('calories', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sodium', models.FloatField()),
                ('potassium', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('suitable_for_diabetes', models.BooleanField()),
                ('suitable_for_bp', models.BooleanField()),
            ],
        ),
    ]
