# Generated by Django 4.0.3 on 2025-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiabitesApp', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='suitable_for_bp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='suitable_for_diabetes',
            field=models.BooleanField(default=False),
        ),
    ]
