# Generated by Django 4.0.3 on 2025-03-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiabitesApp', '0003_alter_food_suitable_for_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='suitable_for_bp',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='suitable_for_diabetes',
            field=models.BooleanField(),
        ),
    ]
